// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  clientAreaSidebar: [{
    type: 'category',
    label: 'Client Area',
    link: {
      type: 'generated-index',
      title: 'Client Area',
      description: 'Learn about the most important Docusaurus concepts!'
    },
    items: [{type:"autogenerated", dirName:"client-area"}],
  }],
  clientareaSidebar: [{type: 'autogenerated', dirName: 'client-area'}],
  gameSidebar: [{type: 'autogenerated', dirName: 'game'}],
  serverSidebar: [{type: 'autogenerated', dirName: 'server'}],
  hostingSidebar: [{type: 'autogenerated', dirName: 'hosting'}],
  companySidebar: [{type: 'autogenerated', dirName: 'company'}],
  docsSidebar: [{type: 'autogenerated', dirName: 'docs'}],
};

module.exports = sidebars;
