// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  generalSidebar: [{ type: "autogenerated", dirName: "general" }],
  gameSidebar: [{ type: "autogenerated", dirName: "game" }],
  serverSidebar: [{ type: "autogenerated", dirName: "server/vps" }],
  hostingSidebar: [{ type: "autogenerated", dirName: "web-hosting" }],
  domainSidebar: [{ type: "autogenerated", dirName: "domain" }],
  companySidebar: [{ type: "autogenerated", dirName: "company" }],
  docsSidebar: [{ type: "autogenerated", dirName: "docs" }],
};

module.exports = sidebars;
